In [1]:
import pandas as pd

In [3]:
import os
print(os.listdir())

['.ipynb_checkpoints', 'archive', 'DataCleaning.ipynb']

In [4]:
import os
print(os.listdir("archive"))

['backpacks.csv', 'bath-robe.csv', 'bath-towels.csv', 'bathroom-accessories.csv', 'bedsheets.csv', 'belts.csv', 'bodysuit.csv', 'boots.csv', 'boxers.csv', 'bra.csv', 'bracelet.csv', 'briefs.csv', 'camisoles.csv', 'candle-holders.csv', 'caps.csv', 'casual-shoes.csv', 'chair-cover.csv', 'clothing-set.csv', 'clutches.csv', 'co-ords.csv', 'Combined_dataset.csv', 'curtains-and-sheers.csv', 'cutlery.csv', 'dinnerware.csv', 'dresses.csv', 'duffel-bag.csv', 'dungarees.csv', 'dupatta.csv', 'earrings.csv', 'ethnic-dresses.csv', 'face-moisturisers.csv', 'face-wash-and-cleanser.csv', 'flats.csv', 'flip-flops.csv', 'floor-mats--dhurries.csv', 'formal-shoes.csv', 'foundation.csv', 'gloves.csv', 'hair-accessory.csv', 'hair-brush-and-comb.csv', 'hair-cream-and-mask.csv', 'hair-masks.csv', 'handbags.csv', 'headphones.csv', 'heels.csv', 'home-fragrance-set.csv', 'innerwear-vests.csv', 'jackets.csv', 'jeans.csv', 'jumpsuit.csv', 'kurta-sets.csv', 'kurtas.csv', 'kurtis.csv', 'lipstick.csv', 'lounge-pants.csv', 'lounge-shorts.csv', 'lounge-tshirts.csv', 'mangalsutra.csv', 'mobile-accessories.csv', 'night-suits.csv', 'nightdress.csv', 'outdoor-masks.csv', 'palazzos.csv', 'perfume-and-body-mist.csv', 'pillow-covers.csv', 'README.md', 'ring.csv', 'runners.csv', 'sandals.csv', 'saree-blouse.csv', 'sarees.csv', 'scarves.csv', 'shampoo-and-conditioner.csv', 'shaving-essentials.csv', 'sherwani.csv', 'shirts.csv', 'shorts.csv', 'showpieces.csv', 'skirts.csv', 'sports-shoes.csv', 'sunglasses.csv', 'sweaters.csv', 'sweatshirts.csv', 'swim-tops.csv', 'table-covers.csv', 'thermal-bottoms.csv', 'tights.csv', 'tops.csv', 'towel-set.csv', 'track-pants.csv', 'trolley-bag.csv', 'trousers.csv', 'trunk.csv', 'tshirts.csv', 'tunics.csv', 'wall-art.csv', 'wallets.csv', 'watches.csv', 'yoga-mats.csv']

In [5]:
df = pd.read_csv("archive/jeans.csv")
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,amount_of_stars,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category
0,18973692,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.2,426,4099.0,57.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":44,""2_stars"":12,""3_stars"":26,""4_star...","[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973692_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,NaN,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
1,18973742,Levis,Men Blue Slim Fit Slash Knee Heavy Fade Stretc...,4.2,182,4399.0,48.0,"""₹2,287.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":12,""2_stars"":9,""3_stars"":19,""4_stars...","[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973742_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
2,19008522,Calvin Klein Jeans,Women Straight Fit Pure Cotton Jeans,3.8,14,7999.0,20.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/190...,...,"{""1_star"":4,""2_stars"":0,""3_stars"":0,""4_stars"":...",NaN,Pla███um ███hio███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-19008522_cae700"",""https://videos.myntasse...",1ST███OOR███O 5█████████MAH███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
3,18974084,Levis,512 Men Navy Blue Slim Tapered Fit Mid-Rise Li...,4.2,135,4399.0,57.0,"""₹1,891.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"{""1_star"":11,""2_stars"":4,""3_stars"":14,""4_stars...","[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",NaN,Eco███xpr███ Pv█████████no ███████████████████...,NaN,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans
4,18873126,KETCH,Men Charcoal Slim Fit Clean Look Light Fade St...,4.0,20,1749.0,64.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"{""1_star"":2,""2_stars"":1,""3_stars"":1,""4_stars"":...","[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",NaN,Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans

In [6]:
df.shape

(57, 24)

In [7]:
df.columns

Index(['product_id', 'title', 'product_description', 'rating', 'ratings_count',
       'initial_price', 'discount', 'final_price', 'currency', 'images',
       'delivery_options', 'product_details', 'breadcrumbs',
       'product_specifications', 'amount_of_stars', 'what_customers_said',
       'seller_name', 'sizes', 'videos', 'seller_information', 'variations',
       'best_offer', 'more_offers', 'category'],
      dtype='object')

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 57 entries, 0 to 56
Data columns (total 24 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   product_id              57 non-null     int64
 1   title                   57 non-null     object
 2   product_description     57 non-null     object
 3   rating                  57 non-null     float64
 4   ratings_count           57 non-null     int64
 5   initial_price           57 non-null     float64
 6   discount                51 non-null     float64
 7   final_price             57 non-null     object
 8   currency                57 non-null     object
 9   images                  57 non-null     object
 10  delivery_options        57 non-null     object
 11  product_details         57 non-null     object
 12  breadcrumbs             57 non-null     object
 13  product_specifications  57 non-null     object
 14  amount_of_stars         57 non-null     object
 15  what_customers_said     43 non-null     object
 16  seller_name             53 non-null     object
 17  sizes                   57 non-null     object
 18  videos                  28 non-null     object
 19  seller_information      53 non-null     object
 20  variations              13 non-null     object
 21  best_offer              57 non-null     object
 22  more_offers             57 non-null     object
 23  category                57 non-null     object
dtypes: float64(3), int64(2), object(19)
memory usage: 10.8+ KB

In [9]:
df.describe()

         product_id     rating  ratings_count  initial_price   discount
count  5.700000e+01  57.000000      57.000000      57.000000  51.000000
mean   1.888785e+07   3.831579      84.859649    3491.035088  52.784314
std    1.295603e+06   0.982555     107.148502    1366.110877  13.177729
min    1.376863e+07   0.000000       0.000000    1399.000000  20.000000
25%    1.880252e+07   3.800000      11.000000    2499.000000  48.500000
50%    1.896998e+07   4.100000      35.000000    3499.000000  55.000000
75%    1.897395e+07   4.300000     116.000000    4299.000000  61.500000
max    2.220388e+07   5.000000     426.000000    7999.000000  75.000000

In [10]:
df.isnull().sum()

product_id                 0
title                      0
product_description        0
rating                     0
ratings_count              0
initial_price              0
discount                   6
final_price                0
currency                   0
images                     0
delivery_options           0
product_details            0
breadcrumbs                0
product_specifications     0
amount_of_stars            0
what_customers_said       14
seller_name                4
sizes                      0
videos                    29
seller_information         4
variations                44
best_offer                 0
more_offers                0
category                   0
dtype: int64

In [11]:
df.fillna(0, inplace=True)

In [12]:
df.drop_duplicates(inplace=True)

In [13]:
df["total_amount"] = df["final_price"] * df["ratings_count"]

In [14]:
df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,18973692,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.2,426,4099.0,57.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973692_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,0,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹..."
1,18973742,Levis,Men Blue Slim Fit Slash Knee Heavy Fade Stretc...,4.2,182,4399.0,48.0,"""₹2,287.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973742_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹2,287.00""""₹2,287.00""""₹2,287.00""""₹2,287.00""""₹..."
2,19008522,Calvin Klein Jeans,Women Straight Fit Pure Cotton Jeans,3.8,14,7999.0,20.0,"""₹4,799.00""",INR,http://assets.myntassets.com/assets/images/190...,...,0,Pla███um ███hio███,"[{""size"":""26"",""value"":""26.0in"",""value_name"":""T...","[""rw-19008522_cae700"",""https://videos.myntasse...",1ST███OOR███O 5█████████MAH███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹4,799.00""""₹4,799.00""""₹4,799.00""""₹4,799.00""""₹..."
3,18974084,Levis,512 Men Navy Blue Slim Tapered Fit Mid-Rise Li...,4.2,135,4399.0,57.0,"""₹1,891.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",0,Eco███xpr███ Pv█████████no ███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹1,891.00""""₹1,891.00""""₹1,891.00""""₹1,891.00""""₹..."
4,18873126,KETCH,Men Charcoal Slim Fit Clean Look Light Fade St...,4.0,20,1749.0,64.0,"""₹629.00""",INR,http://assets.myntassets.com/assets/images/188...,...,"[{""percentage"":""100"",""value_name"":""Fit, Just R...",Sup███om ███,"[{""size"":""30"",""value"":""30.0in"",""value_name"":""T...",0,Plo███o- ███ 1s█████████Sui███████████████████...,"[{},{},{}]","{""applicable_on"":""Orders above Rs. 749 (only o...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹629.00""""₹629.00""""₹629.00""""₹629.00""""₹629.00""""..."

In [15]:
filtered_df = df[df["rating"] > 4]
filtered_df.head()

,product_id,title,product_description,rating,ratings_count,initial_price,discount,final_price,currency,images,...,what_customers_said,seller_name,sizes,videos,seller_information,variations,best_offer,more_offers,category,total_amount
0,18973692,Levis,Men Blue 65504 Skinny Fit Mid Rise Light Fade ...,4.2,426,4099.0,57.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973692_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,0,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹..."
1,18973742,Levis,Men Blue Slim Fit Slash Knee Heavy Fade Stretc...,4.2,182,4399.0,48.0,"""₹2,287.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""56"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973742_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹2,287.00""""₹2,287.00""""₹2,287.00""""₹2,287.00""""₹..."
3,18974084,Levis,512 Men Navy Blue Slim Tapered Fit Mid-Rise Li...,4.2,135,4399.0,57.0,"""₹1,891.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""55"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...",0,Eco███xpr███ Pv█████████no ███████████████████...,0,"{""applicable_on"":""Orders above Rs. 1499 (only ...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹1,891.00""""₹1,891.00""""₹1,891.00""""₹1,891.00""""₹..."
8,18973648,Levis,Men Blue 511 Slim Fit Light Fade Stretchable J...,4.2,290,4099.0,0.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""83"",""value_name"":""Fit, Just Ri...",Lev███tra███ In█████████td,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973648_cae700"",""https://videos.myntasse...",Eco███xpr███ Pv█████████no ███████████████████...,0,"{""best_price"":""3689"",""coupon_code"":""NORETURNS1...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹..."
9,18973888,Levis,Men Skinny Fit Heavy Fade Stretchable Jeans,4.4,333,4099.0,0.0,"""₹4,099.00""",INR,http://assets.myntassets.com/assets/images/189...,...,"[{""percentage"":""74"",""value_name"":""Fit, Just Ri...",Vis███ St███,"[{""size"":""28"",""value"":""28.0in"",""value_name"":""T...","[""rw-18973888_cae700"",""https://videos.myntasse...",3rd███oor███o. █████████Mai███████████████████...,0,"{""applicable_on"":""Purchase of 3 or more items""...","[{""offer_name"":""10% Instant Discount on IndusI...",jeans,"""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹4,099.00""""₹..."

In [16]:
df.to_csv("cleaned_jeans.csv", index=False)